@startuml
skinparam classAttributeIconSize 0


abstract class DSOperation {
-diff : function
-patch : function
-availableTypeOperation : string
__
+addNewOperation(newOperation, newType) 
+setOperation(contentType)
--abstract--
{abstract}+diff(oldContent, newContent) : array
{abstract}+patch(oldContent, edits): string
}

class DSTextOperation{
-dmp : diff_match_patch
+diff(oldContent, newContent) : array
+patch(oldContent, edits) : string
}

abstract class DSLoop{
-url : string
-contents : string
-shadow : string
-myVer : number
-yourVer : number
-edits : Map
-dsOperation : DSOperation
-deleteEdits(versionNumber)
#makeEdits(content)
#receivedEdits(responseEdits)
--abstract--
{abstract}+runLoop()
}

class DSLoopClient {
+runLoop()
}

class DSLoopServer {
+runLoop()
}

DSLoop *--> DSOperation
DSLoopClient --|> DSLoop
DSLoopServer --|> DSLoop

DSOperation *-->  DSTextOperation

@enduml
